---
driver                 :
    # TRAVIS: local 
    # NO TRAVIS: vagrant
    name               : <%= if ENV['TRAVIS'] then 'localhost' else 'vagrant' end  %>

provisioner:
    name               : ansible_push
    verbose            : "vvvv"
    ansible_config     : "test/ansible.cfg"
    idempotency_test   : True
    # TRAVIS: True
    # NO TRAVIS: False
    sudo               : <%= if ENV['TRAVIS'] then 'True' else 'False' end  %>

platforms:
    # travistravis 
     - name                      : <%= if ENV['TRAVIS'] then 'travis' else 'ubuntu-14.04' end %>
       provisioner               :
         raw_arguments           : <%= if ENV['TRAVIS'] then '-c local' else '' end %>
       # Should be safily ignored by Travis since connection local
       driver:
         box: ubuntu/trusty64
       customize:
        cpus   : 2
        memory : 2048 


suites:
  - name            : group
    provisioner     :
        playbook    : "test/application/group.yml"
        extra_vars  : { 'kitchen_connection': 'smart', 'kitchen_hosts': '<%= if ENV['TRAVIS'] then 'localhost' else 'all' end %>' }

  - name            : simple
    provisioner     :
        playbook    : "test/application/simple.yml"
        extra_vars  : { 'kitchen_connection': 'smart', 'kitchen_hosts': '<%= if ENV['TRAVIS'] then 'localhost' else 'all' end %>' }

  - name            : advanced
    provisioner     :
        playbook    : "test/application/advanced.yml"
        extra_vars  : { 'kitchen_connection': 'smart', 'kitchen_hosts': '<%= if ENV['TRAVIS'] then 'localhost' else 'all' end %>' }

  - name            : source-files
    provisioner     :
        playbook    : "test/application/source_files.yml"
        extra_vars  : { 'kitchen_connection': 'smart', 'kitchen_hosts': '<%= if ENV['TRAVIS'] then 'localhost' else 'all' end %>' }

  - name            : source-databag
    provisioner     :
        playbook    : "test/application/source_databag.yml"
        extra_vars  : { 'kitchen_connection': 'smart', 'kitchen_hosts': '<%= if ENV['TRAVIS'] then 'localhost' else 'all' end %>' }

  - name            : multi-source-files
    provisioner     :
        playbook    : "test/application/multi_source_files.yml"
        extra_vars  : { 'kitchen_connection': 'smart', 'kitchen_hosts': '<%= if ENV['TRAVIS'] then 'localhost' else 'all' end %>' }

  - name            : team
    provisioner     :
        playbook    : "test/application/team.yml"
        extra_vars  : { 'kitchen_connection': 'smart', 'kitchen_hosts': '<%= if ENV['TRAVIS'] then 'localhost' else 'all' end %>' }

  - name            : extra-simple
    provisioner     :
        playbook    : "test/application/extra_simple.yml"
        extra_vars  : { 'kitchen_connection': 'smart', 'kitchen_hosts': '<%= if ENV['TRAVIS'] then 'localhost' else 'all' end %>' }

  - name            : extra-advanced
    provisioner     :
        playbook    : "test/application/extra_advanced.yml"
        extra_vars  : { 'kitchen_connection': 'smart', 'kitchen_hosts': '<%= if ENV['TRAVIS'] then 'localhost' else 'all' end %>' }