---
driver                 :
    name               : localhost

provisioner:
    name               : ansible_push
    verbose            : "vvvv"
    ansible_config     : "test/ansible.cfg"
    idempotency_test   : True
    sudo               : True


platforms:
    - name                      : travis
      provisioner               :
        raw_arguments           : "-c local"

suites:
  - name            : group
    provisioner     :
        playbook    : "test/application/group.yml"
        extra_vars  : { 'kitchen_connection': 'smart' }

  - name            : simple
    provisioner     :
        playbook    : "test/application/simple.yml"
        extra_vars  : { 'kitchen_connection': 'smart' }

  - name            : advanced
    provisioner     :
        playbook    : "test/application/advanced.yml"
        extra_vars  : { 'kitchen_connection': 'smart' }

  - name            : source-files
    provisioner     :
        playbook    : "test/application/source_files.yml"
        extra_vars  : { 'kitchen_connection': 'smart' }

  - name            : source-databag
    provisioner     :
        playbook    : "test/application/source_databag.yml"
        extra_vars  : { 'kitchen_connection': 'smart' }

  - name            : multi-source-files
    provisioner     :
        playbook    : "test/application/multi_source_files.yml"
        extra_vars  : { 'kitchen_connection': 'smart' }

  - name            : team
    provisioner     :
        playbook    : "test/application/team.yml"
        extra_vars  : { 'kitchen_connection': 'smart' }
