---
driver:
  name: vagrant

provisioner:
  name: shell
  script: test/run_kitchen.sh

platforms:

platforms:
    - name: ubuntu-14.04
      driver:
        box: ubuntu/trusty64
        synced_folders:
         - [ "<%= puts Dir.pwd %>", "/mnt/shared/<%= puts File.basename(Dir.pwd) %>"]
# - [ "<%= puts Dir.pwd %>", "/mnt/shared/"]
suites:
  - name: default