---
driver                    :
    name                  : <%= if ENV['TRAVIS'] then 'localhost' else 'vagrant' end  %>
    box                   : "ubuntu/trusty64"
    customize             :
         cpus             : 2
         memory           : 2048 

provisioner:
    name                  : ansible_push
    verbose               : "vvvv"
    ansible_config        : "test/ansible.cfg"
    idempotency_test      : True
    sudo                  : <%= if ENV['TRAVIS'] then 'True' else 'False' end  %>
    raw_arguments         : <%= if ENV['TRAVIS'] then '-c local' else '' end %>
    extra_vars            : { 'kitchen_connection': '<%= if ENV["TRAVIS"] then "local" else "smart" end %>', 'kitchen_hosts': '<%= if ENV["TRAVIS"] then "localhost" else "all" end %>' }

platforms:
 - name                   : "ubuntu-v1"
   provisioner            :
     ansible_playbook_bin : "$(ansible-version path v1)ansible-playbook"

 - name                   : "ubuntu-v2"
   provisioner            :
     ansible_playbook_bin : "$(ansible-version path v2)ansible-playbook"

 - name                   : docker-u14-v2
   provisioner            :
     ansible_playbook_bin : "$(ansible-version path v2)ansible-playbook"
   driver_config          :
     image                : quay.io/hellofresh/kitchen-base
     platform             : ubuntu
   driver                 :
    name                  : docker

suites:
  - name                  : group
    provisioner           :
        playbook          : "test/application/group.yml"

  - name                  : simple
    provisioner           :
        playbook          : "test/application/simple.yml"

  - name                  : selected_users
    provisioner           :
        playbook          : "test/integration/selected_users/run.yml"

  - name                  : advanced
    provisioner           :
        playbook          : "test/application/advanced.yml"

  - name                  : source-files
    provisioner           :
        playbook          : "test/application/source_files.yml"

  - name                  : source-databag
    provisioner           :
        playbook          : "test/application/source_databag.yml"

  - name                  : multi-source-files
    provisioner           :
        playbook          : "test/application/multi_source_files.yml"

  - name                  : team
    provisioner           :
        playbook          : "test/application/team.yml"

  - name                  : extra-simple
    provisioner           :
        playbook          : "test/application/extra_simple.yml"

  - name                  : extra-advanced
    provisioner           :
        playbook          : "test/application/extra_advanced.yml"

  - name                  : extra-team
    provisioner           :
        playbook          : "test/application/extra_team.yml"       