---

- name: groups | Create per user group
  group:
    name="{{ item.name }}"
    state="{{ item.state | default("present") }}"
  with_items: usermanage_servers # replace with user
  when: usermanage_create_per_user_group

- name: groups | Create groups
  group:
  args: "{{ item }}"
  with_items: usermanage_groupsdb
  when: usermanage_groups is defined and usermanage_groupsdb is not None