---

- name: single | Debug Users /tmp/debugUser.{{inventory_hostname}}-{{item.account}}
  template:
     src=debug_users.j2
     dest="/tmp/debugUser.{{inventory_hostname}}-{{item.account}}"
  with_items: usermanage_servers
  when: usermanage_debug is defined and usermanage_debug

- name: single | Manage Linux Users accounts
  user:
    name="{{ item.account }}"
    state="{{ item.state | default("present") }}"
    comment="{{ item.comment | default(omit) }}"
    groups="{{ item.groups | default(omit) }}"
    shell="{{ item.shell | default(usermanage_default_shell) }}"
    remove="{{ item.remove | default(usermanage_default_remove) }}"
    force=yes
    append=True
  with_items: usermanage_servers

#- name: single | Mange authorized_keys for multi access to same user
#  authorized_key:
#     user="{{item.0.account}}"
#     state="{{'absent' if 'delete' in LinuxUsers[item.0.account] else item.1.state if item.1.state is defined else defaultState}}"
#     key="{{LinuxUsers[item.1.user].pubkey}}"
#     manage_dir="yes"
#     key_options="{{item.1.key_options if item.1.key_options is defined else ''}}"
#  with_subelements:
#      - usermanage_servers
#      - userkeys
#  register: keyrc
#  failed_when: "'failed' in keyrc and 'getpwnam' not in keyrc.msg"

